[General]
StartMinimized=false
WindowMode=0

[Translation]
Backend=1
Instance=http://127.0.0.1:5805
LibreTranslateDirect=true
LibreTranslateApiKey=
PrimaryLanguage=zh-CN
SecondaryLanguage=en
ForceSourceAutodetect=false
ForceTranslationAutodetect=false

[MainWindow]
CurrentEngine=4
AutoTranslate=false
ShowPrivacyPopup=false

[Buttons]
Source=en, zh-CN
Translation=zh-CN, en
CheckedSource=0
CheckedTranslation=0

[Connection]
ProxyType=2

[TTS]
Backend=0

[Shortcuts]
TranslateSelection=Ctrl+Alt+E
ShowMainWindow=Ctrl+Alt+C
